services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: production
    container_name: trampo-app-staging-api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - users
      - tasks
      - rabbitmq
      - postgres
    env_file:
      - apps/api-gateway/.env.staging
    environment:
      - NODE_ENV=staging

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: production
    container_name: trampo-app-staging-auth
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - apps/auth/.env.staging
    environment:
      - NODE_ENV=staging

  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
      target: production
    container_name: trampo-app-staging-users
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - apps/users/.env.staging
    environment:
      - NODE_ENV=staging

  tasks:
    build:
      context: .
      dockerfile: apps/tasks/Dockerfile
      target: production
    container_name: trampo-app-staging-tasks
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - apps/tasks/.env.staging
    environment:
      - NODE_ENV=staging

  rabbitmq:
    image: rabbitmq:3-management
    container_name: trampo-app-staging-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data_staging:/var/lib/rabbitmq

  postgres:
    image: postgres:15-alpine
    container_name: trampo-app-staging-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trampo
      POSTGRES_PASSWORD: trampo123
      POSTGRES_DB: trampodb_staging
    volumes:
      - pgdata_staging:/var/lib/postgresql/data

volumes:
  pgdata_staging:
  rabbitmq_data_staging:
