name: CI Production

on:
  push:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Set secrets as env vars
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_PRODUCTION }}" >> $GITHUB_ENV
          echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL_PRODUCTION }}" >> $GITHUB_ENV

      - name: Lint
        run: npx nx lint

      - name: Build all apps
        run: npx nx build

      - name: Run unit tests
        run: npx nx test

      - name: Run e2e tests
        run: npx nx run users:test:e2e
